spring:
  profiles:
    include: local

mybatis:
  type-aliases-package: com.dore.shop.model
  mapper-locations: classpath:mappers/*.xml
  type-handlers-package: com.dore.shop.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

